### PR TITLE
Feature encryptall

### PR DESCRIPTION
**Pull request by johnwiesel**
I have added optional AES encryption to both blob storage in local Cassandra and parsed data (parsed message details) in local Cassandra. It is configurable in the yaml files.

### CODE REVIEW

**Comment by rstml** [comment]
Hi, it looks like you merged changes from master branch to your work branch. Can you please do git rebase instead? It's hard to review and can't be automatically merged.

**Comment by johnwiesel** [comment]
Something in my git history does look messy. I'll investigate and post an update tomorrow. Sorry about that.

**Comment by johnwiesel** [comment]
created a new pull request with a clean git history...

**Comment by brainztorm** [comment]
Cool ! :)
Thanks to you both, have a great day :)

**Pull request closed without merging**
